/**
 * SyncLime Companion - Background Service Worker / Script
 * Latest Manifest V3 compliant
 * Handles port discovery (default 14221, range 14221-14230, or custom user port),
 * context menus, hotkeys, and Netscape cookie synchronization.
 */

const DEFAULT_PORT = 14221;
const PORT_RANGE = [14221, 14222, 14223, 14224, 14225, 14226, 14227, 14228, 14229, 14230];

// Convert browser cookie array to standard Netscape cookie format for yt-dlp
function cookiesToNetscape(cookies) {
  if (!cookies || !Array.isArray(cookies) || cookies.length === 0) return "";

  const header =
    "# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# Generated by SyncLime Companion Extension\n\n";
  const lines = cookies.map((c) => {
    let domain = c.domain || "";
    const isDomain = domain.startsWith(".");
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = Math.round(c.expirationDate || Date.now() / 1000 + 86400 * 365);
    const name = c.name || "";
    const value = c.value || "";
    return `${domain}\t${isDomain ? "TRUE" : "FALSE"}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`;
  });

  return header + lines.join("\n") + "\n";
}

// Probes a single port to check if SyncLime's Axum server is alive
async function pingPort(port) {
  try {
    const res = await fetch(`http://127.0.0.1:${port}/health`, {
      signal: AbortSignal.timeout(400),
    });
    if (res.ok) {
      const data = await res.json();
      if (data.status === "ok") {
        return { ok: true, version: data.version };
      }
    }
  } catch {
    // Port closed or unresponsive
  }
  return { ok: false };
}

// Discover the active port based on user preference or automatic range probing
async function getActivePort() {
  let portMode = "auto";
  let customPort = null;

  try {
    const stored = await chrome.storage.local.get(["port_mode", "custom_port", "synclime_port"]);
    portMode = stored.port_mode || "auto";
    customPort = stored.custom_port ? parseInt(stored.custom_port, 10) : null;

    // If user specified a manual custom port, test and use it directly
    if (portMode === "custom" && customPort && !isNaN(customPort)) {
      const ping = await pingPort(customPort);
      if (ping.ok) {
        return { port: customPort, mode: "custom", version: ping.version, isClashed: false };
      }
      return { port: customPort, mode: "custom", version: null, offline: true, isClashed: false };
    }

    // In auto mode: First try the default first port (14221)
    const firstPing = await pingPort(DEFAULT_PORT);
    if (firstPing.ok) {
      await chrome.storage.local.set({ synclime_port: DEFAULT_PORT });
      return { port: DEFAULT_PORT, mode: "auto", version: firstPing.version, isClashed: false };
    }

    // Check cached active port next if it's already in the range
    if (stored.synclime_port && stored.synclime_port !== DEFAULT_PORT) {
      const cachedPing = await pingPort(stored.synclime_port);
      if (cachedPing.ok) {
        return {
          port: stored.synclime_port,
          mode: "auto",
          version: cachedPing.version,
          isClashed: true,
        };
      }
    }
  } catch (err) {
    console.debug("Failed reading storage:", err);
  }

  // If port 14221 clashed or is busy, probe the remaining ports in range 14222..=14230
  for (const port of PORT_RANGE.slice(1)) {
    const ping = await pingPort(port);
    if (ping.ok) {
      await chrome.storage.local.set({ synclime_port: port });
      return { port, mode: "auto", version: ping.version, isClashed: true };
    }
  }

  // Fallback if desktop app is offline
  return { port: DEFAULT_PORT, mode: "auto", version: null, offline: true, isClashed: false };
}

// Send URL and session cookies to SyncLime Inbox
async function sendToSyncLime(targetUrl, tabTitle = "") {
  if (!targetUrl || targetUrl.startsWith("chrome://") || targetUrl.startsWith("about:")) {
    showNotification("Invalid URL", "Browser internal pages cannot be downloaded.", "warning");
    return { success: false, message: "Invalid URL" };
  }

  const portInfo = await getActivePort();
  const port = portInfo.port;

  // Extract cookies for domain only if optional permission is currently granted
  let netscapeCookies = "";
  try {
    const hasCookiesPerm =
      chrome.permissions && chrome.permissions.contains
        ? await chrome.permissions.contains({ permissions: ["cookies"] })
        : false;

    if (hasCookiesPerm && chrome.cookies) {
      const cookies = await chrome.cookies.getAll({ url: targetUrl });
      if (cookies && cookies.length > 0) {
        netscapeCookies = cookiesToNetscape(cookies);
      }
    }
  } catch (err) {
    console.debug("Cookie extraction skipped or not authorized:", err);
  }

  try {
    const response = await fetch(`http://127.0.0.1:${port}/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        url: targetUrl,
        title: tabTitle || undefined,
        cookies: netscapeCookies || undefined,
      }),
    });

    if (!response.ok) {
      throw new Error(`Server returned HTTP ${response.status}`);
    }

    const resData = await response.json();
    if (resData.success) {
      if (resData.already_exists) {
        showNotification(
          "Already in Inbox",
          `This URL is already in your SyncLime queue: ${targetUrl}`,
          "info",
        );
      } else {
        showNotification("Sent to SyncLime Inbox", `Queued: ${tabTitle || targetUrl}`, "success");
      }
      return { success: true, data: resData, portInfo };
    } else {
      showNotification("SyncLime Error", resData.message || "Failed to enqueue URL", "error");
      return { success: false, message: resData.message, portInfo };
    }
  } catch (err) {
    console.error(`Failed connecting to SyncLime on port ${port}:`, err);
    showNotification(
      "SyncLime Offline",
      `Cannot connect to SyncLime on port ${port}. Please make sure the desktop app is running.`,
      "error",
    );
    return { success: false, offline: true, message: err.message, portInfo };
  }
}

function showNotification(title, message) {
  try {
    chrome.notifications.create({
      type: "basic",
      iconUrl: "icons/48x48.png",
      title: `SyncLime: ${title}`,
      message,
      priority: 1,
    });
  } catch (err) {
    console.debug("Notification error:", err);
  }
}

// Setup Context Menus
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "synclime-send-link",
    title: "Send to SyncLime Inbox",
    contexts: ["page", "link", "video", "audio"],
  });
});

// Handle Context Menu clicks
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId === "synclime-send-link") {
    const url = info.linkUrl || info.srcUrl || info.pageUrl || tab?.url;
    const title = tab?.title || "";
    if (url) {
      await sendToSyncLime(url, title);
    }
  }
});

// Handle Keyboard Shortcuts (Alt+S)
chrome.commands.onCommand.addListener(async (command) => {
  if (command === "send-to-synclime") {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab && tab.url) {
      await sendToSyncLime(tab.url, tab.title);
    }
  }
});

// Message listener from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "sendToSyncLime") {
    sendToSyncLime(request.url, request.title).then(sendResponse);
    return true; // Keep channel open for async response
  }

  if (request.action === "checkHealth") {
    getActivePort().then(async (portInfo) => {
      const ping = await pingPort(portInfo.port);
      sendResponse({
        online: ping.ok,
        port: portInfo.port,
        mode: portInfo.mode,
        isClashed: portInfo.isClashed,
        version: ping.version,
      });
    });
    return true;
  }

  if (request.action === "savePortSettings") {
    const { mode, customPort } = request;
    chrome.storage.local.set({ port_mode: mode, custom_port: customPort }).then(() => {
      getActivePort().then(sendResponse);
    });
    return true;
  }

  if (request.action === "scanPortRange") {
    (async () => {
      const results = [];
      for (const port of PORT_RANGE) {
        const ping = await pingPort(port);
        results.push({ port, online: ping.ok, version: ping.version });
      }
      sendResponse({ range: PORT_RANGE, results });
    })();
    return true;
  }
});
