/**
 * SyncLime Companion Background Service Worker / Script
 * Handles port discovery, context menus, hotkeys, and Netscape cookie synchronization.
 */

const DEFAULT_PORT = 14221;
const PORT_RANGE = [14221, 14222, 14223, 14224, 14225, 14226, 14227, 14228, 14229, 14230];

// Convert browser cookie array to Netscape format
function cookiesToNetscape(cookies) {
  if (!cookies || !Array.isArray(cookies) || cookies.length === 0) return "";
  
  const header = "# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by SyncLime Companion Extension\n\n";
  const lines = cookies.map((c) => {
    let domain = c.domain || "";
    const isDomain = domain.startsWith(".");
    const path = c.path || "/";
    const secure = c.secure ? "TRUE" : "FALSE";
    const expiry = Math.round(c.expirationDate || (Date.now() / 1000 + 86400 * 365));
    const name = c.name || "";
    const value = c.value || "";
    return `${domain}\t${isDomain ? "TRUE" : "FALSE"}\t${path}\t${secure}\t${expiry}\t${name}\t${value}`;
  });
  
  return header + lines.join("\n") + "\n";
}

// Discover which port SyncLime desktop app is bound to
async function getActivePort() {
  // Check cached port first
  try {
    const stored = await chrome.storage.local.get(["synclime_port"]);
    if (stored.synclime_port) {
      try {
        const res = await fetch(`http://127.0.0.1:${stored.synclime_port}/health`, {
          signal: AbortSignal.timeout(400),
        });
        if (res.ok) {
          const data = await res.json();
          if (data.status === "ok") return stored.synclime_port;
        }
      } catch {
        // Port changed or down, scan below
      }
    }
  } catch (err) {
    console.debug("Failed reading storage:", err);
  }

  // Probe port range
  for (const port of PORT_RANGE) {
    try {
      const res = await fetch(`http://127.0.0.1:${port}/health`, {
        signal: AbortSignal.timeout(350),
      });
      if (res.ok) {
        const data = await res.json();
        if (data.status === "ok") {
          await chrome.storage.local.set({ synclime_port: port });
          return port;
        }
      }
    } catch {
      // Continue probe
    }
  }

  return DEFAULT_PORT;
}

// Send URL and session cookies to SyncLime Inbox
async function sendToSyncLime(targetUrl, tabTitle = "") {
  if (!targetUrl || targetUrl.startsWith("chrome://") || targetUrl.startsWith("about:")) {
    showNotification("Invalid URL", "Browser internal pages cannot be downloaded.", "warning");
    return { success: false, message: "Invalid URL" };
  }

  const port = await getActivePort();

  // Extract cookies for domain
  let netscapeCookies = "";
  try {
    const cookies = await chrome.cookies.getAll({ url: targetUrl });
    if (cookies && cookies.length > 0) {
      netscapeCookies = cookiesToNetscape(cookies);
    }
  } catch (err) {
    console.warn("Could not retrieve cookies for domain:", err);
  }

  try {
    const response = await fetch(`http://127.0.0.1:${port}/add`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        url: targetUrl,
        title: tabTitle || undefined,
        cookies: netscapeCookies || undefined,
      }),
    });

    if (!response.ok) {
      throw new Error(`Server returned HTTP ${response.status}`);
    }

    const resData = await response.json();
    if (resData.success) {
      if (resData.already_exists) {
        showNotification("Already in Inbox", `This URL is already in your SyncLime queue: ${targetUrl}`, "info");
      } else {
        showNotification("Sent to SyncLime Inbox", `Queued: ${tabTitle || targetUrl}`, "success");
      }
      return { success: true, data: resData };
    } else {
      showNotification("SyncLime Error", resData.message || "Failed to enqueue URL", "error");
      return { success: false, message: resData.message };
    }
  } catch (err) {
    console.error("Failed connecting to SyncLime desktop daemon:", err);
    showNotification(
      "SyncLime Offline",
      "SyncLime desktop application is not running. Launch SyncLime first to capture media.",
      "error"
    );
    return { success: false, offline: true, message: err.message };
  }
}

function showNotification(title, message, type = "info") {
  try {
    chrome.notifications.create({
      type: "basic",
      iconUrl: "icons/48x48.png",
      title: `SyncLime: ${title}`,
      message: message,
      priority: 1,
    });
  } catch (err) {
    console.debug("Notification error:", err);
  }
}

// Setup Context Menus
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: "synclime-send-link",
    title: "Send to SyncLime Inbox",
    contexts: ["page", "link", "video", "audio"],
  });
});

// Handle Context Menu clicks
chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  if (info.menuItemId === "synclime-send-link") {
    const url = info.linkUrl || info.srcUrl || info.pageUrl || tab?.url;
    const title = tab?.title || "";
    if (url) {
      await sendToSyncLime(url, title);
    }
  }
});

// Handle Keyboard Shortcuts
chrome.commands.onCommand.addListener(async (command) => {
  if (command === "send-to-synclime") {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
    if (tab && tab.url) {
      await sendToSyncLime(tab.url, tab.title);
    }
  }
});

// Message listener from popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "sendToSyncLime") {
    sendToSyncLime(request.url, request.title).then(sendResponse);
    return true; // Keep channel open for async response
  }
  if (request.action === "checkHealth") {
    getActivePort().then(async (port) => {
      try {
        const res = await fetch(`http://127.0.0.1:${port}/health`, {
          signal: AbortSignal.timeout(500),
        });
        if (res.ok) {
          const data = await res.json();
          sendResponse({ online: true, port: port, version: data.version });
          return;
        }
      } catch {
        // unreachable
      }
      sendResponse({ online: false, port: port });
    });
    return true;
  }
});
